const uiIcons={"play": "<svg class=\"ui-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M9 5l11 7-11 7z\" fill=\"currentColor\" stroke=\"none\"/></svg>", "next": "<svg class=\"ui-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"m9 5 7 7-7 7\"/></svg>", "prev": "<svg class=\"ui-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"m15 5-7 7 7 7\"/></svg>", "arrow": "<svg class=\"ui-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M4 12h16m-7-7 7 7-7 7\"/></svg>", "external": "<svg class=\"ui-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M7 17 17 7M7 7h10v10\"/></svg>", "close": "<svg class=\"ui-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"m6 6 12 12M18 6 6 18\"/></svg>", "full": "<svg class=\"ui-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M9 4H4v5m11-5h5v5M4 15v5h5m11-5v5h-5\"/></svg>"};
const sectors={
gastro:{hero:'Mynp4ZV_l0k',credit:'Suempol / program kulinarny',line:'Od pierwszego apetytu do pierwszej wizyty.',ideas:[['Wasz smak','Przygotowanie, składniki i gotowy talerz.'],['Wasza ekipa','Co szef kuchni poleca na pierwszy raz.'],['Wasze miejsce','Wnętrze i atmosfera wspólnego stołu.'],['Wasz moment','Lunch, nowe menu lub oferta sezonowa.']],films:[['Nocc64MIf-0','FANEX','Hollywood / Sos Teriyaki','Nocc64MIf-0'],['Mynp4ZV_l0k','SUEMPOL','Program kulinarny','Mynp4ZV_l0k']]},
beauty:{hero:'pilot',credit:'Pilot WP / realizacja BBF',line:'Zaufanie zaczyna się przed pierwszą wizytą.',ideas:[['Pierwsza wizyta','Jak wygląda konsultacja i przyjęcie gościa.'],['Wasz zespół','Specjalista odpowiada na pytania klientów.'],['Wasza praca','Precyzja wykonania i detale usługi.'],['Wasz klimat','Przestrzeń i atmosfera, do której chce się wracać.']],films:[['pilot','PILOT WP','Bez umowy. Bez anteny.','8XqkdzyIj-0'],['Xe6u1hNzOdk','FEZIP','Para idealna','Xe6u1hNzOdk']]},
hotel:{hero:'praga',credit:'Cinematic Praga / realizacja BBF',line:'Pokażcie pobyt, który można sobie wyobrazić.',ideas:[['Pierwsze wrażenie','Wejście, przywitanie i charakter miejsca.'],['Wasze pokoje','Co czeka na gościa po przyjeździe.'],['Przebieg pobytu','Udogodnienia i przestrzenie wspólne.'],['Wasza oferta','Wybrany pobyt, wydarzenie lub usługa.']],films:[['praga','M.ST. WARSZAWA','Cinematic Praga','Sh7jShWrWlM'],['agh','AGH','Fascynują nas wasze błędy','Gd7pDtzLTFI']]},
sport:{hero:'ISxKiJYmMfk',credit:'Frens / Randka z pieskiem',line:'Niech pierwszy krok zacznie się od Waszego filmu.',ideas:[['Pierwszy raz','Co zabrać i czego można się spodziewać.'],['Wasz zespół','Instruktor lub gospodarz odpowiada na pytania.'],['Wasza energia','Fragment zajęć lub wspólnej zabawy.'],['Zaproszenie','Nowa grupa, wydarzenie lub oferta spotkań.']],films:[['agh','AGH','Fascynują nas wasze błędy','Gd7pDtzLTFI'],['ISxKiJYmMfk','FRENS','Randka z pieskiem','ISxKiJYmMfk']]}
};
const paths=['<rect x="4" y="7" width="28" height="23" rx="2"/><path d="m14 13 10 6-10 6Z"/>','<circle cx="18" cy="11" r="6"/><path d="M6 32v-4a12 12 0 0 1 24 0v4"/>','<path d="m3 17 15-13 15 13M7 15v17h22V15M14 32V21h8v11"/>','<circle cx="18" cy="18" r="14"/><path d="M18 9v10l7 4"/>'];
const reelIdeas={
gastro:[['OD PATELNI DO TALERZA','Kucharz kończy danie. Nagrywamy smażenie, sos i podanie do stołu.','DANIE W 3 UJĘCIACH'],['CO ZAMÓWIĆ PIERWSZY RAZ?','Szef poleca jedno danie i mówi dlaczego. Widzimy składniki i gotowy talerz.','POLECENIE SZEFA'],['WIECZÓR U WAS','Goście wchodzą, kelner nalewa wino, na stole ląduje kolacja.','ATMOSFERA LOKALU'],['NOWE DANIE W MENU','Zbliżenie na danie, jego nazwa i składniki. Na końcu: zaproszenie na spróbowanie.','NOWOŚĆ I ZAPROSZENIE']],
beauty:[['JAK WYGLĄDA ZABIEG?','Pokazujemy przygotowanie stanowiska, przebieg zabiegu i jego zakończenie.','WIZYTA KROK PO KROKU'],['JAK SIĘ PRZYGOTOWAĆ?','Specjalistka odpowiada na jedno pytanie, które często słyszy przed wizytą.','ODPOWIEDŹ EKSPERTKI'],['CO ROBIMY INACZEJ?','Zbliżenia dłoni i narzędzi. Specjalistka wyjaśnia jeden ważny etap pracy.','DETAL USŁUGI'],['GODZINA DLA SIEBIE','Herbata, spokojne wnętrze, masaż. Pokazujemy wizytę oczami gościa.','DOŚWIADCZENIE SPA']],
hotel:[['ZOBACZCIE TEN POKÓJ','Otwieramy drzwi. Pokazujemy łóżko, łazienkę i widok z okna.','ROOM TOUR'],['CO JEST NA ŚNIADANIE?','Kawa, przygotowanie jednego dania i gotowy stół. Krótkie polecenie kucharza.','HOTEL OD KUCHNI'],['24 GODZINY U WAS','Przyjazd, odpoczynek, kolacja i poranek. Skrót pobytu z perspektywy gościa.','POMYSŁ NA POBYT'],['CO ZAWIERA PAKIET?','Pracownik mówi, co obejmuje oferta. Pokazujemy pokój i wybrane atrakcje.','KONKRETNA OFERTA']],
sport:[['PIERWSZY RAZ NA SIŁOWNI?','Trener pokazuje wejście, szatnię i pierwsze ćwiczenie. Mówi, co zabrać.','PIERWSZA WIZYTA'],['POZNAJCIE TRENERA','Trener mówi, z kim pracuje i w czym pomaga. Widzimy fragment treningu.','OSOBA I SPECJALIZACJA'],['TAK WYGLĄDAJĄ ZAJĘCIA','Rozgrzewka, wspólne ćwiczenia i finał zajęć. Prawdziwi ludzie, prawdziwa energia.','ZAJĘCIA OD ŚRODKA'],['RUSZA NOWA GRUPA','Instruktor zaprasza na konkretny trening. Na ekranie: termin i sposób zapisów.','ZAPROSZENIE DO ZAPISÓW']]};
let selectedSector=Object.hasOwn(sectors,new URLSearchParams(location.search).get('branza'))?new URLSearchParams(location.search).get('branza'):'gastro';
function sector(key){selectedSector=Object.hasOwn(sectors,key)?key:'gastro';document.querySelectorAll('[data-sector]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.sector===selectedSector)));document.querySelector('#offer-line').textContent='To przykłady. Wybierzemy tematy dla Was.';document.querySelector('#ideas').innerHTML=reelIdeas[selectedSector].map((a,i)=>`<article class="idea reel-idea"><div class="idea-top"><span>ROLKA 0${i+1}</span><svg viewBox="0 0 36 36" aria-hidden="true">${paths[i]}</svg></div><div class="idea-type">${a[2]}</div><h3>${a[0]}</h3><p>${a[1]}</p><span class="idea-format">9:16 / SOCIAL MEDIA</span></article>`).join('');renderMarket(selectedSector);}
let current=0;const slides=[...document.querySelectorAll('main>section')];const stage=document.querySelector('#stage');
function fit(){const scale=Math.min(innerWidth/1440,innerHeight/900);stage.style.transform=`translate(-50%,-50%) scale(${scale})`;}
function show(n){const player=document.querySelector('#reel-screen iframe');if(player){player.remove();document.querySelector('#play-reel').hidden=false;}current=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.classList.toggle('active',i===current);s.inert=i!==current;s.setAttribute('aria-hidden',String(i!==current));});document.querySelector('#counter').textContent=String(current+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');document.querySelector('#previous').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;document.querySelectorAll('.dot').forEach((b,i)=>{b.classList.toggle('active',i===current);b.setAttribute('aria-current',i===current?'step':'false')});const activeId=['premium','film'].includes(slides[current].id)?'pakiety':slides[current].id;document.querySelectorAll('header a[href^="#"]').forEach(a=>{const active=a.getAttribute('href')==='#'+activeId;a.classList.toggle('current',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});history.replaceState(null,'','#'+slides[current].id);}
document.querySelector('#dots').innerHTML=slides.map((s,i)=>`<button class="dot" aria-label="Slajd ${i+1}: ${s.dataset.label||s.id}" data-go="${i}"></button>`).join('');document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>show(+b.dataset.go)));document.querySelector('#previous').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const i=slides.findIndex(s=>'#'+s.id===a.getAttribute('href'));if(i>=0){e.preventDefault();show(i);}}));document.addEventListener('keydown',e=>{if(document.querySelector('#video-dialog').open)return;if(e.target.closest('button,a')&&e.key===' ')return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();show(current+1)}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1)});let start=null;document.querySelector('main').addEventListener('touchstart',e=>{start=e.target.closest('button,a,iframe,input')?null:[e.changedTouches[0].clientX,e.changedTouches[0].clientY]},{passive:true});document.querySelector('main').addEventListener('touchend',e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start[0],dy=e.changedTouches[0].clientY-start[1];if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.4)show(current+(dx<0?1:-1));start=null},{passive:true});document.querySelector('#fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}};addEventListener('resize',fit);fit();show(Math.max(0,slides.findIndex(s=>'#'+s.id===location.hash)));

document.querySelector('#play-reel').addEventListener('click',()=>{const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/IefIrlS3bn0?autoplay=1&rel=0&playsinline=1';frame.title='Big Bear Film - Showreel';frame.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;document.querySelector('#play-reel').hidden=true;document.querySelector('#reel-screen').append(frame);});

const portfolio=[
['pilot.webp','Pilot WP','Bez umowy. Bez anteny.','8XqkdzyIj-0'],['agh.webp','AGH','Fascynują nas wasze błędy','Gd7pDtzLTFI'],['SBNOQinz1Y4.jpg','Strabiscan','Technologia blisko ludzi','SBNOQinz1Y4'],['dCgproXrgE8.jpg','Volkswagen CPO','Historia zakupu','dCgproXrgE8'],['PqNWTu6cqlw.jpg','Xiaomi','Redmi Note 15 / Yeti','PqNWTu6cqlw'],['XZyAyVq9w4w.jpg','Suempol','Odkryj rybę na nowo','XZyAyVq9w4w'],['Mynp4ZV_l0k.webp','Suempol','Gotowanie / bakłażan i łosoś','Mynp4ZV_l0k'],['Nocc64MIf-0.webp','Fanex','Hollywood / Teriyaki','Nocc64MIf-0'],['gastrofan.webp','Fanex','Gastrofan 2025','N9zZweZIo2g'],['ISxKiJYmMfk.webp','Frens','Randka z pieskiem','ISxKiJYmMfk'],['mW_rk44x-Rk.webp','Fundacja Urszuli Jaworskiej','Czas nas goni','mW_rk44x-Rk'],['praga.webp','M.st. Warszawa','Cinematic Praga','Sh7jShWrWlM']];
document.querySelector('#films').innerHTML=portfolio.map(f=>`<button class="work-card" data-video="${f[3]}" data-title="${f[1]} / ${f[2]}"><div class="work-image"><img src="${f[0]}" alt="Kadr: ${f[2]}"><span>${uiIcons.play}</span></div><div class="work-caption"><strong>${f[1]}</strong><span>${f[2]}</span></div></button>`).join('');
const market={
gastro:[['DWRG-CAiB1Z','FOLGA','Smak w detalu','Jedzenie i nalewane wino w zbliżeniu. Produkt staje się gotowym pomysłem na kolację.','@folga.krakow'],['DcrFkUSOyq4','FAMA','Kuchnia od środka','Kuchnia w ruchu i gotowe danie. Widać przygotowanie, nie tylko efekt na talerzu.','@fama.krk'],['Ddbqo7aOkYj','LUIZJANA','Od składnika do talerza','Krojenie i składanie tatara. Proces pokazuje świeżość składników i precyzję kucharza.','@restauracja.luizjana.bydgoszcz']],
hotel:[['Da0Gz9GgK00','NOBU WARSAW','Rzemiosło i doświadczenie','Szef układa sushi na talerzu. Praca rąk pokazuje standard hotelowej restauracji.','@nobuhotelwarsaw'],['DdRac4DtxV2','RAFFLES EUROPEJSKI','Powód, by przyjść','Koktajl, muzyka i termin wydarzenia. Po filmie wiadomo, na co i kiedy przyjść.','@raffleseuropejski'],['DO6CTz_ldYF','H15 BOUTIQUE','Miejsce na Wasz moment','Patio, kawa i spokojne wnętrze. Gość widzi miejsce na odpoczynek lub spotkanie.','@h15_boutique']],
beauty:[['DdJ85d1tSfF','TAO TAO SPA','Poczuj ten spokój','Od herbaty do masażu kamieniami. Relacja z wizyty pozwala wyobrazić sobie własny relaks.','@sekundawkuchni × @tao.tao.spa'],['DdGP_QHih9W','DANUCERA','Ekspertka wyjaśnia','Ekspertka omawia etapy rytuału. Klient dowiaduje się, co czeka go podczas zabiegu.','@danucerapolska'],['DDuiLZPsYkC','SUŁTANA SPA','Zobacz, co Cię czeka','Etapy head spa pokazane z bliska. Usługa staje się zrozumiała bez długiego opisu.','@sultanaspa_krakow']],
sport:[['DctBBGhNa1i','BESTER GYM','Nowa przestrzeń','Nowe maszyny i większy klub to konkretny powód do odwiedzin.','@bestergym'],['DdOIgFHteAD','SINCERE LADIES','Poznajcie trenerów','Ludzie przed sprzętem. Łatwiej zrobić pierwszy krok.','@sincere.ladies'],['DWMdkF-CIr8','KULTURE TRAINING CLUB','Znajdź swoje miejsce','Zaproszenie dla różnych poziomów zaawansowania obniża próg wejścia.','@kulturetrainingclub']]};

function renderMarket(key){document.querySelectorAll('[data-market]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.market===key)));document.querySelector('#market-grid').innerHTML=market[key].map((f,i)=>`<article class="market-card"><button class="market-clean" data-instagram="${f[0]}" data-title="${f[1]}" aria-label="Odtwórz rolkę ${f[1]}"><img src="ig-${f[0]}.webp" alt="Kadr z rolki ${f[1]}"><span class="clean-play" aria-hidden="true">${uiIcons.play}</span><span class="clean-watch">OBEJRZYJ ROLKĘ</span></button><div class="market-caption"><h3>${f[1]}</h3><b>${f[2]}</b><p>${f[3]}</p><a href="https://www.instagram.com/reel/${f[0]}/" target="_blank" rel="noopener">${f[4]} ↗</a></div></article>`).join('');}
document.querySelectorAll('[data-market],[data-sector]').forEach(b=>b.onclick=()=>sector(b.dataset.market||b.dataset.sector));sector(selectedSector);
// Remove external players when moving away so audio cannot continue off-screen.
const showSlide=show;show=function(n){if(slides[current]?.id==='konkurencja')document.querySelector('#market-grid').replaceChildren();showSlide(n);if(slides[current]?.id==='konkurencja')renderMarket(selectedSector);};
const dialog=document.querySelector('#video-dialog');function closeVideo(){dialog.close();document.querySelector('#video-host').replaceChildren();}
document.querySelectorAll('[data-video]').forEach(b=>b.onclick=()=>{document.querySelector('#video-title').textContent=b.dataset.title;dialog.classList.remove('instagram');document.querySelector('#video-source').textContent='Otwórz w YouTube ↗';dialog.classList.toggle('portrait',b.dataset.portrait==='true');document.querySelector('#video-host').innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${b.dataset.video}?autoplay=1&rel=0&playsinline=1" title="${b.dataset.title}" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`;document.querySelector('#video-source').href='https://www.youtube.com/watch?v='+b.dataset.video;dialog.showModal();});document.querySelector('#close-video').onclick=closeVideo;dialog.addEventListener('cancel',e=>{e.preventDefault();closeVideo()});dialog.addEventListener('click',e=>{if(e.target===dialog)closeVideo()});

// Load the official renderer only after the dialog is visible.
let instagramLoader=null, instagramRequest=0, instagramPost=null;
function loadInstagram(){
 if(window.instgrm?.Embeds)return Promise.resolve();
 if(instagramLoader)return instagramLoader;
 instagramLoader=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://www.instagram.com/embed.js';script.async=true;const timeout=setTimeout(()=>{script.remove();instagramLoader=null;reject(new Error('Instagram timeout'));},15000);script.onload=()=>{clearTimeout(timeout);if(window.instgrm?.Embeds)resolve();else{instagramLoader=null;reject(new Error('Instagram unavailable'));}};script.onerror=()=>{clearTimeout(timeout);script.remove();instagramLoader=null;reject(new Error('Instagram unavailable'));};document.head.append(script);});return instagramLoader;
}
async function renderInstagram(){
 const request=++instagramRequest;const post=instagramPost;if(!post)return;
 const host=document.querySelector('#video-host');host.replaceChildren();
 const note=document.querySelector('#instagram-status');note.textContent='Ładowanie odtwarzacza Instagrama…';note.hidden=false;
 const block=document.createElement('blockquote');block.className='instagram-media';block.dataset.instgrmPermalink='https://www.instagram.com/reel/'+post.id+'/';block.dataset.instgrmVersion='14';block.style.margin='0';block.style.width='100%';block.style.minWidth='0';const link=document.createElement('a');link.href=block.dataset.instgrmPermalink;link.target='_blank';link.rel='noopener';link.textContent='Rolka '+post.title;block.append(link);host.append(block);
 try{await loadInstagram();if(request!==instagramRequest||!dialog.open)return;window.instgrm.Embeds.process();note.textContent='Dotknij przycisku odtwarzania na filmie.';}catch{if(request===instagramRequest&&dialog.open)note.textContent='Instagram nie odpowiedział. Spróbuj ponownie lub otwórz oryginał.';}
}
const igControls=document.createElement('div');igControls.id='instagram-controls';igControls.innerHTML='<p id="instagram-status" role="status"></p><button id="instagram-retry" type="button">Wczytaj ponownie ↻</button>';document.querySelector('#video-host').before(igControls);
document.querySelector('#instagram-retry').onclick=renderInstagram;
dialog.addEventListener('close',()=>{instagramRequest++;instagramPost=null;});
document.querySelector('#market-grid').addEventListener('click',e=>{const b=e.target.closest('[data-instagram]');if(!b)return;instagramPost={id:b.dataset.instagram,title:b.dataset.title};document.querySelector('#video-title').textContent=b.dataset.title;dialog.classList.remove('portrait');dialog.classList.add('instagram');const link=document.querySelector('#video-source');link.href='https://www.instagram.com/reel/'+b.dataset.instagram+'/';link.textContent='Otwórz oryginał na Instagramie ↗';document.querySelector('#video-host').replaceChildren();dialog.showModal();renderInstagram();});
