const sectors={
gastro:{hero:'Mynp4ZV_l0k',credit:'Suempol / program kulinarny',line:'Od pierwszego apetytu do pierwszej wizyty.',ideas:[['Wasz smak','Przygotowanie, składniki i gotowy talerz.'],['Wasza ekipa','Co szef kuchni poleca na pierwszy raz.'],['Wasze miejsce','Wnętrze i atmosfera wspólnego stołu.'],['Wasz moment','Lunch, nowe menu lub oferta sezonowa.']],films:[['Nocc64MIf-0','FANEX','Hollywood / Sos Teriyaki','Nocc64MIf-0'],['Mynp4ZV_l0k','SUEMPOL','Program kulinarny','Mynp4ZV_l0k']]},
beauty:{hero:'pilot',credit:'Pilot WP / realizacja BBF',line:'Zaufanie zaczyna się przed pierwszą wizytą.',ideas:[['Pierwsza wizyta','Jak wygląda konsultacja i przyjęcie gościa.'],['Wasz zespół','Specjalista odpowiada na pytania klientów.'],['Wasza praca','Precyzja wykonania i detale usługi.'],['Wasz klimat','Przestrzeń i atmosfera, do której chce się wracać.']],films:[['pilot','PILOT WP','Bez umowy. Bez anteny.','8XqkdzyIj-0'],['Xe6u1hNzOdk','FEZIP','Para idealna','Xe6u1hNzOdk']]},
hotel:{hero:'praga',credit:'Cinematic Praga / realizacja BBF',line:'Pokażcie pobyt, który można sobie wyobrazić.',ideas:[['Pierwsze wrażenie','Wejście, przywitanie i charakter miejsca.'],['Wasze pokoje','Co czeka na gościa po przyjeździe.'],['Przebieg pobytu','Udogodnienia i przestrzenie wspólne.'],['Wasza oferta','Wybrany pobyt, wydarzenie lub usługa.']],films:[['praga','M.ST. WARSZAWA','Cinematic Praga','Sh7jShWrWlM'],['agh','AGH','Fascynują nas wasze błędy','Gd7pDtzLTFI']]},
sport:{hero:'ISxKiJYmMfk',credit:'Frens / Randka z pieskiem',line:'Niech pierwszy krok zacznie się od Waszego filmu.',ideas:[['Pierwszy raz','Co zabrać i czego można się spodziewać.'],['Wasz zespół','Instruktor lub gospodarz odpowiada na pytania.'],['Wasza energia','Fragment zajęć lub wspólnej zabawy.'],['Zaproszenie','Nowa grupa, wydarzenie lub oferta spotkań.']],films:[['agh','AGH','Fascynują nas wasze błędy','Gd7pDtzLTFI'],['ISxKiJYmMfk','FRENS','Randka z pieskiem','ISxKiJYmMfk']]}
};
const paths=['<rect x="4" y="7" width="28" height="23" rx="2"/><path d="m14 13 10 6-10 6Z"/>','<circle cx="18" cy="11" r="6"/><path d="M6 32v-4a12 12 0 0 1 24 0v4"/>','<path d="m3 17 15-13 15 13M7 15v17h22V15M14 32V21h8v11"/>','<circle cx="18" cy="18" r="14"/><path d="M18 9v10l7 4"/>'];
function sector(key){const s=sectors[key]||sectors.gastro;document.querySelectorAll('[data-sector]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.sector===key)));document.querySelector('#hero-img').src=''+s.hero+'.webp';document.querySelector('#hero-img').alt='Kadr z realizacji BBF: '+s.credit;document.querySelector('#hero-credit').textContent='Kadr z realizacji BBF / '+s.credit;document.querySelector('#offer-line').textContent=s.line;document.querySelector('#ideas').innerHTML=s.ideas.map((a,i)=>`<article class="idea"><div class="idea-top"><span>0${i+1}</span><svg viewBox="0 0 36 36" aria-hidden="true">${paths[i]}</svg></div><h3>${a[0]}</h3><p>${a[1]}</p></article>`).join('');document.querySelector('#films').innerHTML=s.films.map(f=>`<a class="film" href="https://www.youtube.com/watch?v=${f[3]}" target="_blank" rel="noopener"><div class="film-picture"><img src="${f[0]}.webp" alt="Kadr z filmu ${f[2]}"><span class="play" aria-hidden="true">▶</span></div><div class="film-caption"><div><h3>${f[2]}</h3><p>${f[1]}</p></div><span>OBEJRZYJ ↗</span></div></a>`).join('');document.querySelector('#proof-note').textContent=key==='gastro'?'Wybrane realizacje BBF. Zakres pokazanych produkcji różni się od pakietów.':'Realizacje BBF z innych branż. Pokazują warsztat, nie zakres cenowy pakietów.';}
document.querySelectorAll('[data-sector]').forEach(b=>b.addEventListener('click',()=>sector(b.dataset.sector)));sector(new URLSearchParams(location.search).get('branza')||'gastro');
let current=0;const slides=[...document.querySelectorAll('main>section')];const stage=document.querySelector('#stage');
function fit(){const scale=Math.min(innerWidth/1440,innerHeight/900);stage.style.transform=`translate(-50%,-50%) scale(${scale})`;}
function show(n){const player=document.querySelector('#reel-screen iframe');if(player){player.remove();document.querySelector('#play-reel').hidden=false;}current=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.classList.toggle('active',i===current);s.inert=i!==current;s.setAttribute('aria-hidden',String(i!==current));});document.querySelector('#counter').textContent=String(current+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');document.querySelector('#previous').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;document.querySelectorAll('.dot').forEach((b,i)=>{b.classList.toggle('active',i===current);b.setAttribute('aria-current',i===current?'step':'false')});history.replaceState(null,'','#'+slides[current].id);}
document.querySelector('#dots').innerHTML=slides.map((s,i)=>`<button class="dot" aria-label="Slajd ${i+1}: ${s.dataset.label||s.id}" data-go="${i}"></button>`).join('');document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>show(+b.dataset.go)));document.querySelector('#previous').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const i=slides.findIndex(s=>'#'+s.id===a.getAttribute('href'));if(i>=0){e.preventDefault();show(i);}}));document.addEventListener('keydown',e=>{if(e.target.closest('button,a')&&e.key===' ')return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();show(current+1)}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1)});let start=null;document.querySelector('main').addEventListener('touchstart',e=>{start=[e.changedTouches[0].clientX,e.changedTouches[0].clientY]},{passive:true});document.querySelector('main').addEventListener('touchend',e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start[0],dy=e.changedTouches[0].clientY-start[1];if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.4)show(current+(dx<0?1:-1));start=null},{passive:true});document.querySelector('#fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}};addEventListener('resize',fit);fit();show(Math.max(0,slides.findIndex(s=>'#'+s.id===location.hash)));

document.querySelector('#play-reel').addEventListener('click',()=>{const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/IefIrlS3bn0?autoplay=1&rel=0&playsinline=1';frame.title='Big Bear Film - Showreel';frame.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;document.querySelector('#play-reel').hidden=true;document.querySelector('#reel-screen').append(frame);});
