const sectors={
gastro:{hero:'Mynp4ZV_l0k',credit:'Suempol / program kulinarny',line:'Od pierwszego apetytu do pierwszej wizyty.',ideas:[['Wasz smak','Przygotowanie, składniki i gotowy talerz.'],['Wasza ekipa','Co szef kuchni poleca na pierwszy raz.'],['Wasze miejsce','Wnętrze i atmosfera wspólnego stołu.'],['Wasz moment','Lunch, nowe menu lub oferta sezonowa.']],films:[['Nocc64MIf-0','FANEX','Hollywood / Sos Teriyaki','Nocc64MIf-0'],['Mynp4ZV_l0k','SUEMPOL','Program kulinarny','Mynp4ZV_l0k']]},
beauty:{hero:'pilot',credit:'Pilot WP / realizacja BBF',line:'Zaufanie zaczyna się przed pierwszą wizytą.',ideas:[['Pierwsza wizyta','Jak wygląda konsultacja i przyjęcie gościa.'],['Wasz zespół','Specjalista odpowiada na pytania klientów.'],['Wasza praca','Precyzja wykonania i detale usługi.'],['Wasz klimat','Przestrzeń i atmosfera, do której chce się wracać.']],films:[['pilot','PILOT WP','Bez umowy. Bez anteny.','8XqkdzyIj-0'],['Xe6u1hNzOdk','FEZIP','Para idealna','Xe6u1hNzOdk']]},
hotel:{hero:'praga',credit:'Cinematic Praga / realizacja BBF',line:'Pokażcie pobyt, który można sobie wyobrazić.',ideas:[['Pierwsze wrażenie','Wejście, przywitanie i charakter miejsca.'],['Wasze pokoje','Co czeka na gościa po przyjeździe.'],['Przebieg pobytu','Udogodnienia i przestrzenie wspólne.'],['Wasza oferta','Wybrany pobyt, wydarzenie lub usługa.']],films:[['praga','M.ST. WARSZAWA','Cinematic Praga','Sh7jShWrWlM'],['agh','AGH','Fascynują nas wasze błędy','Gd7pDtzLTFI']]},
sport:{hero:'ISxKiJYmMfk',credit:'Frens / Randka z pieskiem',line:'Niech pierwszy krok zacznie się od Waszego filmu.',ideas:[['Pierwszy raz','Co zabrać i czego można się spodziewać.'],['Wasz zespół','Instruktor lub gospodarz odpowiada na pytania.'],['Wasza energia','Fragment zajęć lub wspólnej zabawy.'],['Zaproszenie','Nowa grupa, wydarzenie lub oferta spotkań.']],films:[['agh','AGH','Fascynują nas wasze błędy','Gd7pDtzLTFI'],['ISxKiJYmMfk','FRENS','Randka z pieskiem','ISxKiJYmMfk']]}
};
const paths=['<rect x="4" y="7" width="28" height="23" rx="2"/><path d="m14 13 10 6-10 6Z"/>','<circle cx="18" cy="11" r="6"/><path d="M6 32v-4a12 12 0 0 1 24 0v4"/>','<path d="m3 17 15-13 15 13M7 15v17h22V15M14 32V21h8v11"/>','<circle cx="18" cy="18" r="14"/><path d="M18 9v10l7 4"/>'];
const reelIdeas={
gastro:[['TAK POWSTAJE NASZ BESTSELLER','Przygotowanie dania','KULISY'],['CO POLECA SZEF?','Jedno pytanie do kucharza','ROZMOWA'],['STOLIK JUŻ NA WAS CZEKA','Wnętrze i atmosfera','MIEJSCE'],['NOWOŚĆ W MENU','Danie sezonowe w zbliżeniu','PRODUKT']],
beauty:[['PIERWSZA WIZYTA? ZOBACZCIE','Wizyta krok po kroku','USŁUGA'],['PYTANIE DO EKSPERTKI','Krótka odpowiedź specjalistki','ROZMOWA'],['TEN DETAL ROBI RÓŻNICĘ','Precyzja pracy z bliska','KULISY'],['CHWILA TYLKO DLA WAS','Atmosfera i rytuał','DOŚWIADCZENIE']],
hotel:[['WASZ WEEKEND ZACZYNA SIĘ TU','Od wejścia do pokoju','POBYT'],['ZAJRZYJCIE DO ŚRODKA','Pokój i jego detale','MIEJSCE'],['TAK SMAKUJE PORANEK','Śniadanie i kawa','DOŚWIADCZENIE'],['POMYSŁ NA NAJBLIŻSZY WEEKEND','Wybrany pakiet pobytowy','OFERTA']],
sport:[['PIERWSZY TRENING BEZ STRESU','Co zabrać i jak zacząć','PORADNIK'],['POZNAJCIE SWOJEGO TRENERA','Jedna osoba, jedno pytanie','ROZMOWA'],['TAKĄ MAMY ENERGIĘ','Fragment wspólnych zajęć','ATMOSFERA'],['DOŁĄCZCIE DO NOWEJ GRUPY','Termin i zaproszenie','OFERTA']]};
let selectedSector=Object.hasOwn(sectors,new URLSearchParams(location.search).get('branza'))?new URLSearchParams(location.search).get('branza'):'gastro';
function sector(key){selectedSector=Object.hasOwn(sectors,key)?key:'gastro';document.querySelectorAll('[data-sector]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.sector===selectedSector)));document.querySelector('#offer-line').textContent='To przykłady. Wybierzemy tematy dla Was.';document.querySelector('#ideas').innerHTML=reelIdeas[selectedSector].map((a,i)=>`<article class="idea reel-idea"><div class="idea-top"><span>ROLKA 0${i+1}</span><svg viewBox="0 0 36 36" aria-hidden="true">${paths[i]}</svg></div><div class="idea-type">${a[2]}</div><h3>${a[0]}</h3><p>${a[1]}</p><span class="idea-format">9:16 / SOCIAL MEDIA</span></article>`).join('');renderMarket(selectedSector);}
let current=0;const slides=[...document.querySelectorAll('main>section')];const stage=document.querySelector('#stage');
function fit(){const scale=Math.min(innerWidth/1440,innerHeight/900);stage.style.transform=`translate(-50%,-50%) scale(${scale})`;}
function show(n){const player=document.querySelector('#reel-screen iframe');if(player){player.remove();document.querySelector('#play-reel').hidden=false;}current=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.classList.toggle('active',i===current);s.inert=i!==current;s.setAttribute('aria-hidden',String(i!==current));});document.querySelector('#counter').textContent=String(current+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');document.querySelector('#previous').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;document.querySelectorAll('.dot').forEach((b,i)=>{b.classList.toggle('active',i===current);b.setAttribute('aria-current',i===current?'step':'false')});const activeId=['premium','film'].includes(slides[current].id)?'pakiety':slides[current].id;document.querySelectorAll('header a[href^="#"]').forEach(a=>{const active=a.getAttribute('href')==='#'+activeId;a.classList.toggle('current',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});history.replaceState(null,'','#'+slides[current].id);}
document.querySelector('#dots').innerHTML=slides.map((s,i)=>`<button class="dot" aria-label="Slajd ${i+1}: ${s.dataset.label||s.id}" data-go="${i}"></button>`).join('');document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>show(+b.dataset.go)));document.querySelector('#previous').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const i=slides.findIndex(s=>'#'+s.id===a.getAttribute('href'));if(i>=0){e.preventDefault();show(i);}}));document.addEventListener('keydown',e=>{if(document.querySelector('#video-dialog').open)return;if(e.target.closest('button,a')&&e.key===' ')return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();show(current+1)}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1)});let start=null;document.querySelector('main').addEventListener('touchstart',e=>{start=[e.changedTouches[0].clientX,e.changedTouches[0].clientY]},{passive:true});document.querySelector('main').addEventListener('touchend',e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start[0],dy=e.changedTouches[0].clientY-start[1];if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.4)show(current+(dx<0?1:-1));start=null},{passive:true});document.querySelector('#fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}};addEventListener('resize',fit);fit();show(Math.max(0,slides.findIndex(s=>'#'+s.id===location.hash)));

document.querySelector('#play-reel').addEventListener('click',()=>{const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/IefIrlS3bn0?autoplay=1&rel=0&playsinline=1';frame.title='Big Bear Film - Showreel';frame.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;document.querySelector('#play-reel').hidden=true;document.querySelector('#reel-screen').append(frame);});

const portfolio=[
['pilot.webp','Pilot WP','Bez umowy. Bez anteny.','8XqkdzyIj-0'],['agh.webp','AGH','Fascynują nas wasze błędy','Gd7pDtzLTFI'],['SBNOQinz1Y4.jpg','Strabiscan','Technologia blisko ludzi','SBNOQinz1Y4'],['dCgproXrgE8.jpg','Volkswagen CPO','Historia zakupu','dCgproXrgE8'],['PqNWTu6cqlw.jpg','Xiaomi','Redmi Note 15 / Yeti','PqNWTu6cqlw'],['XZyAyVq9w4w.jpg','Suempol','Odkryj rybę na nowo','XZyAyVq9w4w'],['Mynp4ZV_l0k.webp','Suempol','Gotowanie / bakłażan i łosoś','Mynp4ZV_l0k'],['Nocc64MIf-0.webp','Fanex','Hollywood / Teriyaki','Nocc64MIf-0'],['gastrofan.webp','Fanex','Gastrofan 2025','N9zZweZIo2g'],['ISxKiJYmMfk.webp','Frens','Randka z pieskiem','ISxKiJYmMfk'],['mW_rk44x-Rk.webp','Fundacja Urszuli Jaworskiej','Czas nas goni','mW_rk44x-Rk'],['praga.webp','M.st. Warszawa','Cinematic Praga','Sh7jShWrWlM']];
document.querySelector('#films').innerHTML=portfolio.map(f=>`<button class="work-card" data-video="${f[3]}" data-title="${f[1]} / ${f[2]}"><div class="work-image"><img src="${f[0]}" alt="Kadr: ${f[2]}"><span>▶</span></div><div class="work-caption"><strong>${f[1]}</strong><span>${f[2]}</span></div></button>`).join('');
const market={
gastro:[['DWRG-CAiB1Z','FOLGA','Smak w detalu','Duet jedzenia i wina. Jeden konkretny powód do wizyty.','@folga.krakow'],['DcrFkUSOyq4','FAMA','Kuchnia od środka','Kulisy pracy pokazują, co stoi za gotowym daniem.','@fama.krk'],['Ddbqo7aOkYj','LUIZJANA','Od składnika do talerza','Proces przygotowania buduje apetyt i pokazuje kunszt.','@restauracja.luizjana.bydgoszcz']],
hotel:[['Da0Gz9GgK00','NOBU WARSAW','Rzemiosło i doświadczenie','Szef kuchni i jego praca dają twarz hotelowej restauracji.','@nobuhotelwarsaw'],['DdRac4DtxV2','RAFFLES EUROPEJSKI','Powód, by przyjść','Koktajl i zaproszenie na konkretny wieczór w Long Barze.','@raffleseuropejski'],['DO6CTz_ldYF','H15 BOUTIQUE','Miejsce na Wasz moment','Patio ma konkretną rolę: kawa, spotkanie, chwila spokoju.','@h15_boutique']],
beauty:[['DdJ85d1tSfF','TAO TAO SPA','Poczuj ten spokój','Doświadczenie gościa pokazuje usługę z perspektywy klienta.','@sekundawkuchni × @tao.tao.spa'],['DdGP_QHih9W','DANUCERA','Ekspertka wyjaśnia','Omówienie rytuału odpowiada na pytania przed wizytą.','@danucerapolska'],['DDuiLZPsYkC','SUŁTANA SPA','Zobacz, co Cię czeka','Pokaz zabiegu ułatwia wyobrażenie sobie własnej wizyty.','@sultanaspa_krakow']],
sport:[['DctBBGhNa1i','BESTER GYM','Nowa przestrzeń','Nowe maszyny i większy klub to konkretny powód do odwiedzin.','@bestergym'],['DdOIgFHteAD','SINCERE LADIES','Poznajcie trenerów','Ludzie przed sprzętem. Łatwiej zrobić pierwszy krok.','@sincere.ladies'],['DWMdkF-CIr8','KULTURE TRAINING CLUB','Znajdź swoje miejsce','Zaproszenie dla różnych poziomów zaawansowania obniża próg wejścia.','@kulturetrainingclub']]};

function renderMarket(key){document.querySelectorAll('[data-market]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.market===key)));document.querySelector('#market-grid').innerHTML=market[key].map((f,i)=>`<article class="market-card"><button class="market-clean" data-instagram="${f[0]}" data-title="${f[1]}" aria-label="Odtwórz rolkę ${f[1]}"><img src="ig-${f[0]}.webp" alt="Kadr z rolki ${f[1]}"><span class="clean-play" aria-hidden="true">▶</span><span class="clean-watch">OBEJRZYJ ROLKĘ ▶</span></button><div class="market-caption"><h3>${f[1]}</h3><b>${f[2]}</b><p>${f[3]}</p><a href="https://www.instagram.com/reel/${f[0]}/" target="_blank" rel="noopener">${f[4]} ↗</a></div></article>`).join('');}
document.querySelectorAll('[data-market],[data-sector]').forEach(b=>b.onclick=()=>sector(b.dataset.market||b.dataset.sector));sector(selectedSector);
// Remove external players when moving away so audio cannot continue off-screen.
const showSlide=show;show=function(n){if(slides[current]?.id==='konkurencja')document.querySelector('#market-grid').replaceChildren();showSlide(n);if(slides[current]?.id==='konkurencja')renderMarket(selectedSector);};
const dialog=document.querySelector('#video-dialog');function closeVideo(){dialog.close();document.querySelector('#video-host').replaceChildren();}
document.querySelectorAll('[data-video]').forEach(b=>b.onclick=()=>{document.querySelector('#video-title').textContent=b.dataset.title;dialog.classList.remove('instagram');document.querySelector('#video-source').textContent='Otwórz w YouTube ↗';dialog.classList.toggle('portrait',b.dataset.portrait==='true');document.querySelector('#video-host').innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${b.dataset.video}?autoplay=1&rel=0&playsinline=1" title="${b.dataset.title}" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`;document.querySelector('#video-source').href='https://www.youtube.com/watch?v='+b.dataset.video;dialog.showModal();});document.querySelector('#close-video').onclick=closeVideo;dialog.addEventListener('cancel',e=>{e.preventDefault();closeVideo()});dialog.addEventListener('click',e=>{if(e.target===dialog)closeVideo()});

document.querySelector('#market-grid').addEventListener('click',e=>{const b=e.target.closest('[data-instagram]');if(!b)return;document.querySelector('#video-title').textContent=b.dataset.title;dialog.classList.remove('portrait');dialog.classList.add('instagram');document.querySelector('#video-host').innerHTML=`<iframe src="https://www.instagram.com/reel/${b.dataset.instagram}/embed/" title="Rolka ${b.dataset.title}" allow="autoplay; encrypted-media; fullscreen" allowfullscreen></iframe>`;const link=document.querySelector('#video-source');link.href='https://www.instagram.com/reel/'+b.dataset.instagram+'/';link.textContent='Nie odtwarza się? Otwórz Instagram ↗';dialog.showModal();});
